#171913621 setup development environment
YvesIraguha/lost-and-found-api pull request #2
Opened 2020-03-26 00:55 UTC by Habinezajanvier

#### What does this PR do?
Setup development environment 
#### Description of Task to be completed?
* Set up mongoose
* set up express
* set up mongodb
#### How should this be manually tested?
* clone the repo and checkout the branch `ch-setup-development-enviroment-#171913621`
* After checking out the branch, then,
* copy the content of `.env` file and paste it in your `.env` file.
* Start the server by running `npm run start`
* copy the **url** given in your console, and then open postman and send a post request on  route **url**/found/ you should get a response or error message
#### What are the relevant pivotal tracker stories?
#171913621

#### Questions:
How can I clone a repo with its branches directly

2020-03-29 12:57 UTC, YvesIraguha requested changes
Hello @Habinezajanvier thanks for the initiative you had for setting up MongoDB, however, on the pull request description, there are no clear steps for setting up MongoDB. It would be nice if you have added a description or a link to a video on how we can set up MongoDB. In addition, ensure that there is a configuration for `development, production, and testing` environments in database connections as both of these environments are crucial for the success of this project. 

Lastly, remove every single content you have in the `controllers` directory, as we do not need it for now. Even models, it would be better to remove them.

2020-03-29 12:57 UTC, YvesIraguha commented on src/db/connection.js
> +    const db_port = process.env.PORTNAME;
```suggestion
    const db_port = process.env.PORT_NAME;
```

2020-03-29 12:57 UTC, YvesIraguha commented on src/db/connection.js
> +    const db_host = process.env.HOSTNAME;
I would like to suggest that you use dash between two words in the same variable

```suggestion
    const db_host = process.env.HOST_NAME;
```

2020-04-06 12:17 UTC, SimonImanigirimpuhwe approved these changes
After reviewing the request by running the app in my local machine I found it working. Therefore, it can be merged.

2020-04-06 12:56 UTC, YvesIraguha requested changes

2020-04-06 12:56 UTC, YvesIraguha commented on src/db/connection.js
> +            }
@Habinezajanvier can you remove these `console.log`?

2020-04-07 13:11 UTC, YvesIraguha approved these changes

2020-04-07 13:11 UTC, merged