#171923516 setup testing environment
YvesIraguha/lost-and-found-api pull request #4
Opened 2020-04-08 21:21 UTC by Habinezajanvier

#### What does this PR do?
* Setting testing environment
#### Description of Task to be completed?
* Setting *jest* for testing
* Installing *supertest* for request testing
#### How should this be manually tested?
* Clone the repo and checkout `ch-setup-testing-environment-#171923516
* run `npm install` to install dependencies
* fill `.env` with correct credentials
* run `npm test`
> you should see a pass of 3 test
#### Any background context you want to provide?
* To make a test fail, you may change any of the test suit in /tests/controller.test.js
#### What are the relevant pivotal tracker stories?
#171923516

2020-04-14 13:27 UTC, YvesIraguha reviewed
Also, the tests fail, when I run them.

2020-04-14 13:27 UTC, YvesIraguha commented on package.json
> +    "@babel/register": "^7.9.0",
This package is a dev-dependency.

2020-04-14 13:27 UTC, YvesIraguha commented on package.json
> +    "morgan": "^1.10.0"
This package is a devDepency

2020-04-14 13:27 UTC, YvesIraguha commented on src/controllers/controller.js
> +        res.json({msg: "successfully saved"})
Actually the record created should also be returned.

2020-04-14 13:27 UTC, YvesIraguha commented on src/controllers/controller.js
> +        res.json({msg: "successfully saved"})
In addition, when I create other records it keeps responding document exist, not sure if that is the intended behavior.

2020-04-14 13:27 UTC, YvesIraguha commented on src/controllers/controller.js
> +module.exports = router;
Add a line at the end of each file

2020-04-15 14:41 UTC, YvesIraguha commented on .vscode/settings.json
> +{
Remove this folder, please. Ignore it.

2020-04-15 14:42 UTC, YvesIraguha requested changes

2020-04-15 14:42 UTC, YvesIraguha commented on tests/controller.test.js
> +
Can you use `es6` please. `import` versus `require()`

2020-04-15 22:51 UTC, SimonImanigirimpuhwe reviewed
I tried to run the test and unfortunately it failed. There were the total 3 fail.

2020-04-19 19:19 UTC, YvesIraguha approved these changes

2020-04-19 19:20 UTC, merged